/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Adapted for Ride Kolkata 3D Canvas Studio
*/

import React from 'react';

/**
 * Type declaration representing the GLTF JSX node and material structure
 * extracted from '/Main Cycle.glb'
 */
export interface MainCycleGltfNodes {
  Chain: { geometry: any };
  Cranks: { geometry: any };
  DamperB: { geometry: any };
  DamperT: { geometry: any };
  Derailleur: { geometry: any };
  Derailleur001: { geometry: any };
  Derailleur002: { geometry: any };
  ForkL_1: { geometry: any };
  ForkL_2: { geometry: any };
  ForkUBars_1: { geometry: any };
  ForkUBars_2: { geometry: any };
  ForkUBars_3: { geometry: any };
  FrameBl: { geometry: any };
  FrameBu_1: { geometry: any };
  FrameBu_2: { geometry: any };
  FrameL_1: { geometry: any };
  FrameL_2: { geometry: any };
  FrameL_3: { geometry: any };
  FrameM_1: { geometry: any };
  FrameM_2: { geometry: any };
  Line1: { geometry: any };
  Line2: { geometry: any };
  PedalL: { geometry: any };
  PedalR: { geometry: any };
  Seat: { geometry: any };
  Spring: { geometry: any };
  wheelF_1: { geometry: any };
  wheelF_2: { geometry: any };
  wheelF_3: { geometry: any };
  wheelR_1: { geometry: any };
  wheelR_2: { geometry: any };
  wheelR_3: { geometry: any };
}

export interface MainCycleGltfMaterials {
  Parts: any;
  CrankDamper: any;
  Fork: any;
  BarsSeatPedals: any;
  Frame: any;
  FrameBlack: any;
  Wheels: any;
  Tires: any;
}

export const MAIN_CYCLE_MODEL_PATH = '/Main Cycle.glb';
